name: Build JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Maven Build"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '1.8' # Use Java version 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml
