name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Maven Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v2

      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 20
          cache: "maven"

      - name: "Set DISPLAY variable"
        run: export DISPLAY=:0

      - name: "Cache Maven dependencies"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: "Build with Maven"
        run: mvn verify
