name: Build JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Maven Build"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '20' # Use Java version 20

      # - name: Clean and Install with Maven
      #   run: mvn clean install -U
        
      - name: Build with Maven
        run: mvn -X package --file pom.xml
