name: Maven Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 20
          cache: "maven"

      - name: "Setup Xvfb"
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99.0" >> $GITHUB_ENV

      - name: "Cache SonarCloud packages"
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: "Cache Maven packages"
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: "Build and Analyze with SonarCloud"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Reikalingas, kad gautumėte PR informaciją
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Jūsų SonarCloud token
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BenasG28_GKL-Clothes-Shop -Dsonar.organization=benasg28 -Dsonar.host.url=https://sonarcloud.io