name: Feature Branch CI

on:
  push:
    branches:
      - feature/all
  pull_request:
    branches:
      - feature/all

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      - name: Build and test
        run: |
          ./mvnw clean compile
          ./mvnw test
